#ifndef NEBULIZER_FAULT_CODES_H_
#define NEBULIZER_FAULT_CODES_H_

typedef enum {
	FAULT_NONE = 0,
	FAULT_INIT_FAILED,
	FAULT_ADC_INIT_FAILED,
	FAULT_UART_INIT_FAILED,
	FAULT_PWM_INIT_FAILED,
	FAULT_TIMER_INIT_FAILED,
	FAULT_SENSOR_NTC_OPEN,
	FAULT_SENSOR_NTC_SHORT,
	FAULT_OVER_TEMP,
	FAULT_LIQUID_EMPTY,
	FAULT_COVER_OPEN,
	FAULT_MIST_BOARD_OFFLINE,
	FAULT_MIST_BOARD_FAULT,
	FAULT_HOST_HEARTBEAT_TIMEOUT,
	FAULT_PROTOCOL_ERROR,
	FAULT_STORAGE_ERROR,
	FAULT_OUTLET1_OVER_TEMP,
	FAULT_KETTLE_OVER_TEMP,
} fault_code_t;

#endif /* NEBULIZER_FAULT_CODES_H_ */
