#ifndef NEBULIZER_PROTOCOL_IDS_H_
#define NEBULIZER_PROTOCOL_IDS_H_

#include <stdint.h>

enum host_frame_type {
	HOST_FRAME_TYPE_CMD = 0x01,
	HOST_FRAME_TYPE_ACK = 0x02,
	HOST_FRAME_TYPE_NACK = 0x03,
	HOST_FRAME_TYPE_STATUS = 0x04,
	HOST_FRAME_TYPE_EVENT = 0x05,
	HOST_FRAME_TYPE_CONFIG = 0x06,
	HOST_FRAME_TYPE_PID = 0x07,
	HOST_FRAME_TYPE_RUNTIME = 0x08,
	HOST_FRAME_TYPE_MAINT = 0x09,
};

enum host_cmd_id {
	HOST_CMD_SET_MODE = 0x10,
	HOST_CMD_SET_TARGET_TEMP = 0x11,
	HOST_CMD_SET_TIME = 0x12,
	HOST_CMD_SET_AIR_LEVEL = 0x13,
	HOST_CMD_SET_MIST_LEVEL = 0x14,
	HOST_CMD_START = 0x20,
	HOST_CMD_PAUSE = 0x21,
	HOST_CMD_RESUME = 0x22,
	HOST_CMD_STOP = 0x23,
	HOST_CMD_GET_STATUS = 0x24,
	HOST_CMD_HEARTBEAT = 0x25,
	HOST_CMD_CLEAR_FAULT = 0x26,
	HOST_CMD_GET_CONFIG = 0x27,
	HOST_CMD_GET_PID = 0x28,
	HOST_CMD_SET_PID = 0x29,
	HOST_CMD_GET_RUNTIME = 0x2A,
	HOST_CMD_ENTER_MAINTENANCE = 0x2B,
	HOST_CMD_EXIT_MAINTENANCE = 0x2C,
	HOST_CMD_MANUAL_SET_FAN = 0x2D,
	HOST_CMD_MANUAL_SET_MIST = 0x2E,
	HOST_CMD_MANUAL_SET_HEAT = 0x2F,
	HOST_CMD_GET_MAINTENANCE = 0x30,
};

enum mist_frame_type {
	MIST_FRAME_TYPE_CMD = 0x31,
	MIST_FRAME_TYPE_ACK = 0x32,
	MIST_FRAME_TYPE_NACK = 0x33,
	MIST_FRAME_TYPE_STATUS = 0x34,
	MIST_FRAME_TYPE_FAULT = 0x35,
};

enum mist_cmd_id {
	MIST_CMD_PING = 0x40,
	MIST_CMD_SET_LEVEL = 0x41,
	MIST_CMD_START = 0x42,
	MIST_CMD_STOP = 0x43,
	MIST_CMD_GET_STATUS = 0x44,
};

enum mist_error_code {
	MIST_ERR_NONE = 0x00,
	MIST_ERR_SAFETY_LOCKED = 0x07,
};

enum mist_fault_code {
	MIST_FAULT_NONE = 0x0000,
	MIST_FAULT_LOW_WATER = 0x0009,
};

typedef enum {
	MIST_LEVEL_OFF = 0,
	MIST_LEVEL_LOW = 1,
	MIST_LEVEL_MID = 2,
	MIST_LEVEL_HIGH = 3,
} mist_level_id_t;

#endif /* NEBULIZER_PROTOCOL_IDS_H_ */
